name: Build and Deploy to Google Compute Engine

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{secrets.GCE_PROJECT}}
  GCE_INSTANCE: ${{secrets.GCE_INSTANCE}}
  GCE_INSTANCE_ZONE: asia-northeast3-a

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest


    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up properties
        run: |
          cd src/main
          mkdir resources
          cd resources
          touch application.yml
          echo "${{ secrets.APPLICATION }}" > application.yml
          cat application.yml

        shell: bash

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test with Gradle
        run: ./gradlew clean build


      - name: 'Set up Cloud Auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      # Setup gcloud CLI
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 390.0.0'
          project_id: ${{secrets.GCE_PROJECT}}


      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - run: |-
          gcloud auth configure-docker gcr.io
      # Build the Docker image
      - name: Build
        run: |-
          docker build --tag "gcr.io/$PROJECT_ID/putl-server" .
      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |-
          docker push "gcr.io/$PROJECT_ID/putl-server"
      - name: Deploy
        run: |-
          gcloud compute instances update-container "$GCE_INSTANCE" \
            --zone "$GCE_INSTANCE_ZONE" \
            --container-image "gcr.io/$PROJECT_ID/putl-server"
